### PR TITLE
Wrap script to docker image

### PR DESCRIPTION
**Pull request by yarkovaleksei**

### CODE REVIEW

**Comment by yarkovaleksei** [comment]
@its5Q Hi. I came across your script here: https://qna.habr.com/q/1366218
I found it useful and decided to make launching the script a little more convenient.

**Comment by yarkovaleksei** [comment]
@its5Q Hi! ))

**Comment by its5Q** [comment]
Hi, sorry, I haven't seen the notification because I was on vacation when you made this PR. I'll quickly take a look and merge it if everything looks good!

**Comment by its5Q** [comment]
Looks good, glad you found my script useful! I'll merge it now.

**Pull request merged**
